name: ci

on:
  push:
    branches: [ master, source ]
  pull_request:
    branches: [ master, source ]

env:
  CACHE_EPOCH: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9  
    - run: git submodule update --init
    - run: python -m pip install nox
    - run: python -m nox
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: output
        single-commit: Yes